USE [master]
GO
/****** Object:  Database [GERENCIA_TAREFAS]    Script Date: 28/07/2024 13:41:09 ******/
CREATE DATABASE [GERENCIA_TAREFAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GERENCIA_TAREFAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GERENCIA_TAREFAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GERENCIA_TAREFAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\GERENCIA_TAREFAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GERENCIA_TAREFAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET  MULTI_USER 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET QUERY_STORE = OFF
GO
USE [GERENCIA_TAREFAS]
GO
/****** Object:  Table [dbo].[HistoricoTarefas]    Script Date: 28/07/2024 13:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HistoricoTarefas](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdTarefas] [bigint] NULL,
	[Altualizacao] [varchar](500) NULL,
	[Comentario] [varchar](500) NULL,
	[DataAtualizacao] [datetime] NULL,
	[IdUsuario] [bigint] NULL,
 CONSTRAINT [PK_HistoricoTarefas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Projetos]    Script Date: 28/07/2024 13:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Projetos](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NULL,
	[IdUsuario] [bigint] NULL,
 CONSTRAINT [PK_Projetos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tarefas]    Script Date: 28/07/2024 13:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tarefas](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Titulo] [varchar](50) NULL,
	[Descricao] [varchar](500) NULL,
	[DataVencimento] [datetime] NULL,
	[Status] [int] NULL,
	[Prioridade] [int] NULL,
	[IdProjeto] [bigint] NULL,
	[DataAtualizacao] [datetime] NULL,
 CONSTRAINT [PK_Tarefas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 28/07/2024 13:41:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NULL,
	[Funcao] [int] NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [GERENCIA_TAREFAS] SET  READ_WRITE 
GO
